language: go

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - go get github.com/tools/godep
  - make restore-deps
  - rsync -az $HOME/gopath/src/github.com/browny/goweb-scaffold $HOME/gopath/src/

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - scripts/coverage --coveralls
