language: go

go:
  - 1.5
  - 1.6

install:
  - go get github.com/tools/godep
  - make restore-deps
  - rsync -az $HOME/gopath/src/github.com/browny/goweb-scaffold $HOME/gopath/src/

script:
  make test

